# Notes:
# In order to publish to github, we need a GitHub token.
# This token should be in ~/.config/goreleaser/github_token
# Then, to release, ensure that the released commit is tagged.
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
    gcflags:
      - "all=-trimpath={{.Env.GOPATH}}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: false
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# where to publish
release:
  github:
    owner: jpillora
    name: sshd-lite
  header: |
    ## Release {{ .Tag }} on {{ .Date }}
    
  # auto-publish?
  draft: false
  # mark as production ready?
  prerelease: false